name: Merge OpenAPI Specs

on:
  push:
    branches:
      - main

jobs:
  merge-openapi-specs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge OpenAPI specs
        run: |
          echo "::group::Merging OpenAPI specs"
          jq -s '.[0] * .[1]' docs/petstore-api-docs.json docs/user-api-docs.json > docs/merged-api-docs.json
          echo "::endgroup::"

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Generate Redoc HTML
        run: |
          mkdir -p public
          redoc-cli bundle docs/merged-api-docs.json -o public/index.html
